# Generated by Django 4.2 on 2025-10-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custid', models.AutoField(primary_key=True, serialize=False)),
                ('custname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('mobile', models.CharField(max_length=12, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('custpassword', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
