# Generated by Django 4.2 on 2025-11-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('mobile', models.CharField(max_length=12, unique=True)),
                ('nationality', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.AutoField(primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=20, unique=True)),
                ('booktitle', models.CharField(max_length=100, unique=True)),
                ('genre', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Publicationyear', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stockavailable', models.IntegerField(blank=True, null=True)),
                ('bookdescription', models.CharField(blank=True, max_length=200, null=True)),
                ('edition', models.CharField(blank=True, max_length=20, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
    ]
