# Generated by Django 4.2 on 2025-11-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchid', models.AutoField(primary_key=True, serialize=False)),
                ('branchname', models.CharField(blank=True, max_length=50, null=True)),
                ('branchlocation', models.CharField(max_length=50)),
                ('branchcountry', models.CharField(blank=True, max_length=50, null=True)),
                ('branchstatus', models.CharField(blank=True, max_length=20, null=True)),
                ('branchnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('branchemail', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inqid', models.AutoField(primary_key=True, serialize=False)),
                ('inqname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=20)),
                ('inqsubject', models.CharField(max_length=20)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'inquiries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('orderdate', models.DateField()),
                ('totalamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderstatus', models.CharField(blank=True, max_length=20, null=True)),
                ('deliveryaddress', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('orderitemid', models.AutoField(primary_key=True, serialize=False)),
                ('paymentdetails', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'orderdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('staffpassword', models.CharField(max_length=20)),
                ('staffrole', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
    ]
