# Generated by Django 4.2 on 2025-11-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_branch_inquiry_order_orderdetail_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('bookTitle', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stockLeft', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Inventory Report',
                'verbose_name_plural': 'Inventory Report',
                'db_table': 'inventory_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('month', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('total_orders', models.IntegerField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Sales Report',
                'verbose_name_plural': 'Sales Report',
                'db_table': 'sales_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoreStatistics',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('totalCustomers', models.IntegerField()),
                ('totalBooks', models.IntegerField()),
                ('totalStaff', models.IntegerField()),
                ('totalOrders', models.IntegerField()),
                ('totalSales', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Store Statistic',
                'verbose_name_plural': 'Store Statistics',
                'db_table': 'quillerbookstorestatistics',
                'managed': False,
            },
        ),
    ]
